version: "3.9"
services:
  redis:
    image: redis/redis-stack
    restart: on-failure
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis-data:/data
    environment:
      REDIS_ARGS: --save 60 1 --notify-keyspace-events KEA
  telegram-bot:
    depends_on:
      - redis
    build:
      context: services/telegram-bot/
    image: itlaboratory/what-a-car-telegram-bot
    restart: on-failure
    env_file:
      - .env
    environment:
      REDIS_HOST: redis://redis:6379
  sravni:
    depends_on:
      - redis
    build:
      context: services/sravni/
    image: itlaboratory/what-a-car-sravni
    restart: on-failure
    environment:
      REDIS_HOST: redis://redis:6379
  autoins:
    depends_on:
      - redis
    build:
      context: services/autoins/
    image: itlaboratory/what-a-car-autoins
    restart: on-failure
    environment:
      REDIS_HOST: redis://redis:6379
  gibdd-captcha-solver:
    build:
      context: ./services/gibdd-captcha-solver/
    image: itlaboratory/what-a-car-gibdd-captcha-solver
    restart: on-failure
    ports:
      - 8080:8080
  gibdd:
    depends_on:
      - gibdd-captcha-solver
      - redis
    build:
      context: ./services/gibdd/
    image: itlaboratory/what-a-car-gibdd
    restart: on-failure
    environment:
      REDIS_HOST: redis://redis:6379
      CAPTCHA_SOLVER_URL: http://gibdd-captcha-solver:8080


  storage:
    build:
      context: services/storage/
    image: itlaboratory/what-a-car-storage
    restart: on-failure
    depends_on:
      - mongo
      - redis
    environment:
      REDIS_HOST: redis://redis:6379
      MONGO_HOST: mongodb://root:root@mongo:27017
  mongo:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
volumes:
  redis-data:
  mongo-data:
