version: "3.9"
services:
  api:
    build:
      context: services/api-gateway/
    image: itlaboratory/what-a-car-api
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - sravni
      - autoins
      - gibdd
      - redis
    environment:
      SRAVNI_HOST: http://sravni:8110
      AUTOINS_HOST: http://autoins:8100
      GIBDD_HOST: http://gibdd:8090
      REDIS_HOST: redis://redis:6379
  sravni:
    build:
      context: services/sravni/
    image: itlaboratory/sravni
    restart: unless-stopped
    ports:
      - 8110:8110
  autoins:
    build:
      context: services/autoins/
    image: itlaboratory/autoins
    restart: unless-stopped
    ports:
      - 8100:8100
  gibdd-captcha-solver:
    build:
      context: ./services/gibdd-captcha-solver/
    image: itlaboratory/gibdd-captcha-solver
    restart: unless-stopped
    ports:
      - 8080:8080
  gibdd:
    build:
      context: ./services/gibdd/
    image: itlaboratory/gibdd
    restart: unless-stopped
    ports:
      - 8090:8090
    depends_on:
      - gibdd-captcha-solver
    environment:
      CAPTCHA_SOLVER_URL: http://gibdd-captcha-solver:8080
  redis:
    image: redis/redis-stack
    restart: unless-stopped
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis-data:/data
    environment:
      REDIS_ARGS: --save 60 1
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
volumes:
  redis-data:
  mongo-data:
