version: "3.9"
services:
  redis:
    image: redis/redis-stack
    restart: on-failure
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - redis-data:/data
    environment:
      REDIS_ARGS: --save 60 1 #--notify-keyspace-events KEA
  telegram-bot:
    depends_on:
      - redis
    build:
      context: services/telegram-bot/
    image: itlaboratory/what-a-car-telegram-bot
    restart: on-failure
    env_file:
      - .env
    environment:
      REDIS_HOST: redis://redis:6379
  sravni:
    depends_on:
      - redis
    build:
      context: services/sravni/
    image: itlaboratory/what-a-car-sravni
    restart: on-failure
    environment:
      REDIS_HOST: redis://redis:6379
      REDIS_EXPIRATION_SEC: 604800
  ingos:
    depends_on:
      - redis
    build:
      context: services/ingos/
    image: itlaboratory/what-a-car-ingos
    restart: on-failure
    environment:
      REDIS_HOST: redis://redis:6379
      REDIS_EXPIRATION_SEC: 604800
  gibdd-captcha-solver:
    depends_on:
      - redis
    build:
      context: ./services/gibdd-captcha-solver/
    image: itlaboratory/what-a-car-gibdd-captcha-solver
    restart: on-failure
    environment:
      REDIS_HOSTNAME: redis
      REDIS_PORT: 6379
    deploy:
      mode: replicated
      replicas: 5
  gibdd-history:
    depends_on:
      - gibdd-captcha-solver
      - redis
    build:
      context: ./services/gibdd/history/
    image: itlaboratory/what-a-car-gibdd-history
    restart: on-failure
    environment:
      REDIS_HOST: redis://redis:6379
      REDIS_EXPIRATION_SEC: 604800
      DEBOUCE_INTERVAL_MS: 60000
  gibdd-accidents:
    depends_on:
      - gibdd-captcha-solver
      - redis
    build:
      context: ./services/gibdd/accidents/
    image: itlaboratory/what-a-car-gibdd-accidents
    restart: on-failure
    environment:
      REDIS_HOST: redis://redis:6379
      REDIS_EXPIRATION_SEC: 604800
      DEBOUCE_INTERVAL_MS: 60000
  gibdd-diagnostic-cards:
    depends_on:
      - gibdd-captcha-solver
      - redis
    build:
      context: ./services/gibdd/diagnosticCards/
    image: itlaboratory/what-a-car-gibdd-diagnostic-cards
    restart: on-failure
    environment:
      REDIS_HOST: redis://redis:6379
      REDIS_EXPIRATION_SEC: 604800
      DEBOUCE_INTERVAL_MS: 60000
  gibdd-fines:
    depends_on:
      - gibdd-captcha-solver
      - redis
    build:
      context: ./services/gibdd/fines/
    image: itlaboratory/what-a-car-gibdd-fines
    restart: on-failure
    environment:
      REDIS_HOST: redis://redis:6379
      REDIS_EXPIRATION_SEC: 604800
      DEBOUCE_INTERVAL_MS: 60000
  gibdd-restrictions:
    depends_on:
      - gibdd-captcha-solver
      - redis
    build:
      context: ./services/gibdd/restrictions/
    image: itlaboratory/what-a-car-gibdd-restrictions
    restart: on-failure
    environment:
      REDIS_HOST: redis://redis:6379
      REDIS_EXPIRATION_SEC: 604800
      DEBOUCE_INTERVAL_MS: 60000
  gibdd-wanted:
    depends_on:
      - gibdd-captcha-solver
      - redis
    build:
      context: ./services/gibdd/wanted/
    image: itlaboratory/what-a-car-gibdd-wanted
    restart: on-failure
    environment:
      REDIS_HOST: redis://redis:6379
      REDIS_EXPIRATION_SEC: 604800
      DEBOUCE_INTERVAL_MS: 60000
  mosreg:
    depends_on:
      - redis
    build:
      context: services/mosreg/
    image: itlaboratory/what-a-car-mosreg
    restart: on-failure
    environment:
      REDIS_HOST: redis://redis:6379
      REDIS_EXPIRATION_SEC: 604800
  storage:
    build:
      context: services/storage/
    image: itlaboratory/what-a-car-storage
    restart: on-failure
    depends_on:
      - mongo
      - redis
    environment:
      REDIS_HOST: redis://redis:6379
      MONGO_HOST: mongodb://root:root@mongo:27017
  mongo:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
#  autoins:
#    depends_on:
#      - redis
#    build:
#      context: services/autoins/
#    image: itlaboratory/what-a-car-autoins
#    restart: on-failure
#    environment:
#      REDIS_HOST: redis://redis:6379
#      REDIS_EXPIRATION_SEC: 604800
#      NAVIGATION_TIMEOUT_MS: 90000
#      ATTEMPTS: 2
#    deploy:
#      mode: replicated
#      replicas: 2
volumes:
  redis-data:
  mongo-data:
